#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# Self-heal Laravel writable directories: files created by root (or under a
# previous UID mapping) would otherwise permanently break cache, session,
# view, and log writes for the sail user.
for dir in /var/www/html/storage /var/www/html/bootstrap/cache; do
    if [ -d "$dir" ]; then
        find "$dir" ! -user sail -exec chown sail:sail {} +
        chmod -R u+rwX "$dir"
    fi
done

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
