<?php

namespace Tests\Feature\Services;

use App\Constants\AuditTier;
use App\Services\AuditReport\AuditMeasurer;
use App\Services\AuditReport\Findings\Severity;
use App\Services\AuditReport\Measurement;
use App\Services\AuditReport\RepositoryFacts;
use App\Services\AuditReport\Scanners\GitleaksScanner;
use App\Services\AuditReport\Scanners\RepoContext;
use App\Services\AuditReport\Scanners\SccScanner;
use App\Services\AuditReport\Tiers\TierProfileResolver;
use Illuminate\Support\Facades\Http;
use Tests\Feature\FeatureTest;

/**
 * The 2026-09-25 skaile-ai/platform report, reduced to the patterns that
 * produced its false positives. Each assertion is one line of the customer's
 * rebuttal that this run must not repeat.
 */
class AuditPrecisionRegressionTest extends FeatureTest
{
    private string $repo;

    protected function setUp(): void
    {
        parent::setUp();

        if (! app(SccScanner::class)->isAvailable() || ! app(GitleaksScanner::class)->isAvailable() || ! app('audit.scanner.semgrep')->isAvailable()) {
            $this->markTestSkipped('scc, gitleaks and semgrep are required for the regression fixture.');
        }

        $this->repo = sys_get_temp_dir().'/precision-'.bin2hex(random_bytes(6));
        $this->buildFixture();
    }

    protected function tearDown(): void
    {
        if (isset($this->repo)) {
            exec('rm -rf '.escapeshellarg($this->repo));
        }

        parent::tearDown();
    }

    private function write(string $path, string $content): void
    {
        @mkdir(dirname($this->repo.'/'.$path), 0755, true);
        file_put_contents($this->repo.'/'.$path, $content);
    }

    private function buildFixture(): void
    {
        // Credential-shaped values are derived at run time: nothing secret-looking is committed.
        $generic = substr(base64_encode(hash('sha256', 'precision-generic', true)), 0, 32);
        $pat = 'ghp_'.substr(hash('sha256', 'precision-pat'), 0, 36);
        $code = fn (int $n, string $prefix = 'x'): string => implode("\n", array_map(fn (int $i): string => "export const {$prefix}{$i} = {$i};", range(1, $n)))."\n";

        $this->write('package.json', json_encode(['workspaces' => ['packages/*'], 'devDependencies' => ['typescript' => '^5']]));
        $this->write('bun.lock', "{\n  \"lockfileVersion\": 1,\n  \"packages\": {\n    \"typescript\": [\"typescript@5.4.5\", \"\", {}, \"sha512-x\"],\n  },\n}\n");
        $this->write('packages/api/package.json', json_encode(['name' => 'api', 'dependencies' => ['@sentry/bun' => '^8']]));
        $this->write('packages/api/src/gif-search.service.ts', "const GIPHY_API_KEY = \"{$generic}\";\n".$code(40, 'g'));
        $this->write('packages/api/src/token.ts', "export const t = '{$pat}';\n");
        $this->write('packages/api/src/session.ts', $code(300, 's'));
        $this->write('packages/api/test/auth.test.ts', "const api_key = \"{$generic}\";\nconst jwt = \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\";\n");
        $this->write('postxl-lock.json', json_encode(['files' => ['a.ts' => ['apiKey' => $generic]]], JSON_PRETTY_PRINT));
        $this->write('packages/db/src/models/User.ts', "/* !!! This is code generated by Prisma. Do not edit directly. !!! */\n".$code(1200, 'u'));
        $this->write('proto/storybook-static/sb-manager/runtime.js', str_repeat('var a=1;', 4000)."\n");
        $this->write('Jenkinsfile', "pipeline { stages { stage('b') { steps { sh 'git clone https://\$GIT_TOKEN@example.com/r.git' } } } }\n");
        $this->write('.github/workflows/ci.yml', "on: push\njobs: {}\n");
        $this->write('CHANGELOG.md', str_repeat("- change\n", 2000));
    }

    private function measure(): Measurement
    {
        Http::fake([(string) config('audit.osv_endpoint') => Http::response(['results' => [['vulns' => []]]])]);

        $context = new RepoContext(path: $this->repo, tier: app(TierProfileResolver::class)->for(AuditTier::DIAGNOSTIC));

        return app(AuditMeasurer::class)->measure($context, ['scc', 'gitleaks', 'osv', 'jscpd', 'semgrep']);
    }

    public function test_the_platform_false_positives_do_not_recur(): void
    {
        $m = $this->measure();
        $facts = RepositoryFacts::from($m->metrics, $m->groups);

        // "CI configured: no" / "test file ratio 0%"
        $this->assertTrue($facts['has_ci']);
        $this->assertSame(['github_actions', 'jenkins'], $facts['ci_systems']);
        $this->assertGreaterThan(0.0, $facts['test_ratio_pct']);

        // "No dependency lockfile"
        $this->assertTrue($m->metrics['manifests']['package.json']['lockfile']);
        $this->assertTrue($m->metrics['manifests']['packages/api/package.json']['lockfile']);
        $this->assertNotContains('dependencies', $m->scores->notMeasured);

        // "No runtime error monitoring"
        $this->assertTrue($m->metrics['tooling']['error_monitoring']);

        // 131 critical credentials → exactly one real key, one possible, the rest fixtures
        $secrets = [];
        foreach ($m->groups as $group) {
            if (str_starts_with($group->ruleFamily, 'secrets.')) {
                $secrets[$group->severity->value] = ($secrets[$group->severity->value] ?? 0) + $group->count;
                foreach ($group->examples as $example) {
                    $this->assertNotSame('postxl-lock.json', $example['path']);
                }
            }
        }
        $this->assertSame(1, $secrets[Severity::CRITICAL->value] ?? 0);
        $this->assertSame(1, $secrets[Severity::HIGH->value] ?? 0);
        $this->assertSame(1, $secrets[Severity::LOW->value] ?? 0);
        $this->assertGreaterThan(0, $m->scores->scores['security_hygiene']);

        // Structure 0 driven by generated Prisma clients and Storybook bundles
        $largest = array_column($m->metrics['largest_files'], 'path');
        $this->assertNotContains('packages/db/src/models/User.ts', $largest);
        $this->assertNotContains('proto/storybook-static/sb-manager/runtime.js', $largest);
        $this->assertNotContains('CHANGELOG.md', $largest);
        $this->assertContains('structure.committed-build-output', array_map(fn ($g) => $g->ruleFamily, $m->groups));
        $this->assertGreaterThan(0, $m->metrics['excluded_summary']['generated'] ?? 0);
    }

    public function test_the_dry_run_command_prints_facts_and_scores(): void
    {
        Http::fake([(string) config('audit.osv_endpoint') => Http::response(['results' => [['vulns' => []]]])]);

        $this->artisan('app:audit-dry-run', ['path' => $this->repo])
            ->expectsOutputToContain('CI configured')
            ->expectsOutputToContain('security_hygiene')
            ->assertSuccessful();
    }
}
