<x-layouts.email>
    <x-slot name="preview">
        {{ __('Your codebase health report is ready') }}
    </x-slot>

    <tr>
        <td class="sm-px-6" style="border-radius: 4px; padding: 48px; font-size: 16px; color: #334155; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05)" bgcolor="#ffffff">
            <p style="margin: 0; line-height: 24px">
                {{ __('Hi :name,', ['name' => $report->auditRequest->name]) }}
            </p>
            <p style="margin: 16px 0 0; line-height: 24px">
                {{ __('Your codebase health report is ready — view it online:') }}
            </p>
            <p style="margin: 16px 0 0; line-height: 24px">
                <a href="{{ $signedUrl }}">{{ __('View my report') }}</a>
                ({{ __('link valid for :days days', ['days' => config('audit.report_link_days')]) }})
            </p>
            @if ($deltas !== null && ($deltas['deltas']['overall'] ?? 0) !== 0)
                <p style="margin: 16px 0 0; line-height: 24px">
                    {{ $deltas['deltas']['overall'] > 0
                        ? __('Good news: overall health is up :d points since your last audit of this repository.', ['d' => $deltas['deltas']['overall']])
                        : __('Heads up: overall health is down :d points since your last audit of this repository.', ['d' => abs($deltas['deltas']['overall'])]) }}
                </p>
            @endif
            <p style="margin: 16px 0 0; line-height: 24px">
                {{ __('This report was generated by automated analysis — scores and findings are derived from measured repository metrics. Reply to this email and a human will walk you through it.') }}
            </p>
        </td>
    </tr>
</x-layouts.email>
