<x-layouts.email>
    <x-slot name="preview">
        {{ __('Your codebase health report is ready') }}
    </x-slot>

    <tr>
        <td class="sm-px-6" style="border-radius: 4px; padding: 48px; font-size: 16px; color: #334155; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05)" bgcolor="#ffffff">
            <p style="margin: 0; line-height: 24px">
                {{ __('Hi :name,', ['name' => $report->auditRequest->name]) }}
            </p>
            <p style="margin: 16px 0 0; line-height: 24px">
                {{ __('Your codebase health report is ready — view it online:') }}
            </p>
            <p style="margin: 16px 0 0; line-height: 24px">
                <a href="{{ $signedUrl }}">{{ __('View my report') }}</a>
                ({{ __('link valid for :days days', ['days' => config('audit.report_link_days')]) }})
            </p>
            <p style="margin: 16px 0 0; line-height: 24px">
                {{ __('This report was generated by automated analysis — scores and findings are derived from measured repository metrics. Reply to this email and a human will walk you through it.') }}
            </p>
        </td>
    </tr>
</x-layouts.email>
